import { IsNotEmpty, IsString, IsEnum } from 'class-validator';

export enum CaseStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESPONSE_REQUESTED = 'RESPONSE_REQUESTED',
  RESPONSE_SUBMITTED = 'RESPONSE_SUBMITTED',
  ARBITRATOR_ASSIGNED = 'ARBITRATOR_ASSIGNED',
  HEARING_SCHEDULED = 'HEARING_SCHEDULED',
  HEARING_COMPLETED = 'HEARING_COMPLETED',
  DELIBERATION = 'DELIBERATION',
  AWARD_ISSUED = 'AWARD_ISSUED',
  CLOSED = 'CLOSED',
  WITHDRAWN = 'WITHDRAWN',
}

export class UpdateCaseStatusDto {
  @IsNotEmpty()
  @IsEnum(CaseStatus)
  status: CaseStatus;
}